[package]
name = "kalgan_string"
version = "0.9.0"
edition = "2018"
description = "A collection of functions for string manipulation used by Kalgan Framework."
homepage = "https://kalgan.eduardocasas.com"
repository = "https://github.com/eduardocasas/kalgan-string"
license = "MIT OR Apache-2.0"